name: health_count
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  json_annotation:
  sqflite: ^2.4.0
  font_awesome_flutter:
  get:
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  intl:
  autocomplete_textfield:
  flutter_native_splash: ^2.4.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/data/workouts.txt
    - assets/imgs/logo.png

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#bf5ae0"
  image: assets/imgs/logo.png
  android_12:
    color: "#bf5ae0"
    image: assets/imgs/logo.png
